framework:
    cache:
        # Redis
        # If using the cc-docker setup, REDIS_URL will be cc-redis and things should work just fine.
        # You can also use your own redis instance or use alternative cache adapters such as
        # https://symfony.com/doc/current/components/cache/adapters/array_cache_adapter.html.
        default_redis_provider: '%env(REDIS_URL)%'

        system: cache.adapter.redis
        app: cache.adapter.redis
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
