doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        auto_generate_proxy_classes: false
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            numeric_functions:
                round: App\DoctrineFunctions\Round
