fos_rest:
    param_fetcher_listener:  true
    body_listener:  true
    routing_loader:
        default_format: json
    zone:
        - { path: '^/api/*' }
        - { path: '^/web/*' }
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], prefer_extension: false }
            - { path: '^/web', priorities: ['json'], prefer_extension: false }
            - { path: '^/', stop: true }
