framework:
    secret: '%env(APP_SECRET)%'
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    default_locale: 'en'
    trusted_hosts: ~
    cache:
        # If using the cc-docker setup, REDIS_URL will be cc-redis and things should work just fine.
        # You can also use your own redis instance or use alternative cache adapters such as
        # https://symfony.com/doc/current/components/cache/adapters/array_cache_adapter.html.
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
