security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        api_key_user_provider:
            id: App\Security\ApiKeyUserProvider
        db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        rest_api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: App\Security\ApiKeyAuthenticator
            provider: api_key_user_provider

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            logout: ~
            provider: db_provider
            guard:
                authenticators:
                    - App\Security\LdapAuthenticator


    access_control:
        - { path: ^/monitoring, roles: [ROLE_USER, ROLE_ANALYST, ROLE_ADMIN]}
        - { path: ^/config, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_API }
        - { path: ^/web, roles: [ROLE_USER, ROLE_ANALYST, ROLE_ADMIN]}

