security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Entity\User
        db_api_provider:
            entity:
                class: App\Entity\User
                property: apiToken

    firewalls:
        # rest_api:
        #     pattern: ^/api
        #     stateless: true
        #     provider: db_api_provider
        #     guard:
        #       authenticators:
        #         - App\Security\TokenAuthenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            logout:
                path: security_logout
                target: index
            provider: db_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\LdapAuthenticator
                entry_point: App\Security\LoginFormAuthenticator


    access_control:
        - { path: ^/monitoring, roles: [ROLE_USER, ROLE_ANALYST, ROLE_ADMIN]}
        - { path: ^/config, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/web, roles: [ROLE_USER, ROLE_ANALYST, ROLE_ADMIN]}
