job:
    type:     rest
    resource: App\Controller\API\JobsController
    prefix:  "api"
configuration:
    type:     rest
    resource: App\Controller\API\ConfigurationController
    prefix:  "web"
tag:
    type:     rest
    resource: App\Controller\API\TagController
    prefix:  "web"
cluster:
    type:     rest
    resource: App\Controller\API\ClusterController
    prefix:  "web"
joblist:
    type:     rest
    resource: App\Controller\API\JobListController
    prefix:  "web"
index:
    path: /
    controller:  App\Controller\IndexViewController::home
imprint:
    path: /imprint
    controller:  App\Controller\IndexViewController::imprint
privacy:
    path: /privacy
    controller:  App\Controller\IndexViewController::privacy
cluster_roof:
    path: /roofline/
    controller:  App\Controller\IndexViewController::roofline
list_jobs:
    path: /monitoring/listjobs/
    controller:  App\Controller\JobViewController::list
list_jobs_tag:
    path: /monitoring/listjobs/{id}
    controller:  App\Controller\JobViewController::listTag
job_tag_types:
    path: /monitoring/tagtypes/
    controller:  App\Controller\JobViewController::listTagTypes
search_jobs:
    path: /monitoring/job/search
    controller:  App\Controller\JobViewController::search
show_job:
    path: /monitoring/job/{id}
    controller:  App\Controller\JobViewController::show
show_job_base:
    path: /monitoring/job/
    controller:  App\Controller\JobViewController::show
search_id:
    path: /monitoring/searchId
    controller:  App\Controller\JobViewController::searchId
user_stat:
    path: /monitoring/user/statistics/
    controller:  App\Controller\StatisticsViewController::users
show_user:
    path: /monitoring/user/{id}
    controller:  App\Controller\UserViewController::show
show_user_base:
    path: /monitoring/user/
    controller:  App\Controller\UserViewController::show
show_group:
    path: /monitoring/group/show/{id}
    controller:  App\Controller\UserViewController::showGroup
edit_group:
    path: /monitoring/group/edit/{id}
    controller:  App\Controller\UserViewController::editGroup
config_user:
    path: /config
    controller:  App\Controller\ConfigViewController::config
config_plot:
    path: /config/plot
    controller:  App\Controller\ConfigViewController::userOptions
config_color:
    path: /config/colormap
    controller:  App\Controller\ConfigViewController::colorMapOptions
config_index:
    path: /admin
    controller:  App\Controller\ConfigViewController::index
user_options:
    path: /admin/user
    controller:  App\Controller\ConfigViewController::userOptions
color_options:
    path: /admin/colormap
    controller:  App\Controller\ConfigViewController::colorMapOptions
default_options:
    path: /admin/default
    controller:  App\Controller\ConfigViewController::defaultOptions
general_options:
    path: /admin/general
    controller:  App\Controller\ConfigViewController::generalOptions
ldap_options:
    path: /admin/ldap
    controller:  App\Controller\ConfigViewController::ldapOptions
cache_options:
    path: /admin/cache
    controller:  App\Controller\ConfigViewController::cacheOptions
list_api_keys:
    path: /admin/apiKeys/
    controller:  App\Controller\ConfigViewController::listApiKeys
edit_api_key:
    path: /admin/apiKeys/{id}
    controller:  App\Controller\ConfigViewController::editApiKey
delete_api_key:
    path: /admin/delete_apiKey/{id}
    controller:  App\Controller\ConfigViewController::deleteApiKey
create_api_key:
    path: /admin/create_apiKey/
    controller:  App\Controller\ConfigViewController::createApiKey
list_user_accounts:
    path: /admin/userAccounts/
    controller:  App\Controller\ConfigViewController::listUserAccounts
edit_user_account:
    path: /admin/userAccounts/{id}
    controller:  App\Controller\ConfigViewController::editUserAccount
delete_user_account:
    path: /admin/delete_userAccount/{id}
    controller:  App\Controller\ConfigViewController::deleteUserAccount
create_user_account:
    path: /admin/create_userAccount/
    controller:  App\Controller\ConfigViewController::createUserAccount
list_clusters:
    path: /admin/clusters/
    controller:  App\Controller\ConfigViewController::listClusters
edit_cluster:
    path: /admin/clusters/{id}
    controller:  App\Controller\ConfigViewController::editCluster
delete_cluster:
    path: /admin/delete_cluster/{id}
    controller:  App\Controller\ConfigViewController::deleteCluster
create_cluster:
    path: /admin/create_cluster/
    controller:  App\Controller\ConfigViewController::createCluster
security_login:
    path: /login
    controller:  App\Controller\SecurityController::login
security_logout:
    path:  /logout
