swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
index:
    path: /
    controller:  Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      route: 'list_jobs'
      permanent: true
imprint:
    path: /imprint
    controller:  App\Controller\IndexViewController::imprint
privacy:
    path: /privacy
    controller:  App\Controller\IndexViewController::privacy
list_jobs:
    path: /monitoring/jobs/
    controller:  App\Controller\JobViewController::list
systems:
    path: /monitoring/systems/
    controller:  App\Controller\SystemViewController::systems
node:
    path: /monitoring/node/{cluster}/{node}
    controller:  App\Controller\SystemViewController::node
analysis:
    path: /monitoring/analysis/
    controller:  App\Controller\JobViewController::analysis
list_jobs_tag:
    path: /monitoring/tag/{id}
    controller:  App\Controller\JobViewController::listTag
job_tag_types:
    path: /monitoring/tags/
    controller:  App\Controller\JobViewController::listTagTypes
show_job:
    path: /monitoring/job/{id}
    controller:  App\Controller\JobViewController::show
search_id:
    path: /monitoring/search/
    controller:  App\Controller\JobViewController::searchId
user_stat:
    path: /monitoring/users/
    controller:  App\Controller\UserViewController::list
show_user:
    path: /monitoring/user/{id}
    controller:  App\Controller\UserViewController::show
config_user:
    path: /config
    controller:  App\Controller\ConfigViewController::config
config_plot:
    path: /config/plot
    controller:  App\Controller\ConfigViewController::userOptions
config_color:
    path: /config/colormap
    controller:  App\Controller\ConfigViewController::colorMapOptions
config_index:
    path: /admin
    controller:  App\Controller\ConfigViewController::index
user_options:
    path: /admin/user
    controller:  App\Controller\ConfigViewController::userOptions
color_options:
    path: /admin/colormap
    controller:  App\Controller\ConfigViewController::colorMapOptions
default_options:
    path: /admin/default
    controller:  App\Controller\ConfigViewController::defaultOptions
general_options:
    path: /admin/general
    controller:  App\Controller\ConfigViewController::generalOptions
ldap_options:
    path: /admin/ldap
    controller:  App\Controller\ConfigViewController::ldapOptions
list_api_keys:
    path: /admin/apiKeys/
    controller:  App\Controller\ConfigViewController::listApiKeys
edit_api_key:
    path: /admin/apiKeys/{id}
    controller:  App\Controller\ConfigViewController::editApiKey
delete_api_key:
    path: /admin/delete_apiKey/{id}
    controller:  App\Controller\ConfigViewController::deleteApiKey
create_api_key:
    path: /admin/create_apiKey/
    controller:  App\Controller\ConfigViewController::createApiKey
list_user_accounts:
    path: /admin/userAccounts/
    controller:  App\Controller\ConfigViewController::listUserAccounts
edit_user_account:
    path: /admin/userAccounts/{id}
    controller:  App\Controller\ConfigViewController::editUserAccount
delete_user_account:
    path: /admin/delete_userAccount/{id}
    controller:  App\Controller\ConfigViewController::deleteUserAccount
create_user_account:
    path: /admin/create_userAccount/
    controller:  App\Controller\ConfigViewController::createUserAccount
security_login:
    path: /login
    controller:  App\Controller\SecurityController::login
security_logout:
    path:  /logout
    controller:  App\Controller\SecurityController::logout
