# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Both values need to be Base64-encoded.
    # TODO: Use environment variable or file instead!
    # Created using:
    #    $keyPair = sodium_crypto_sign_keypair();
    #    echo base64_encode(sodium_crypto_sign_secretkey($keyPair));
    #    echo base64_encode(sodium_crypto_sign_publickey($keyPair));
    jwt_private_key: "dtPC/6dWJFKZK7KZ78CvWuynylOmjBFyMsUWArwmodOTN9itjL5POlqdZkcnmpJ0yPm4pRaCrvgFaFAbpyik/Q=="
    jwt_public_key: "kzfYrYy+TzpanWZHJ5qSdMj5uKUWgq74BWhQG6copP0="

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $jwtPrivateKey: '%jwt_private_key%'
            $jwtPublicKey: '%jwt_public_key%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Colormaps/'

    # configure which implementation of MetricDataRepository
    # to inject in other services such as JobData and JobStats
    App\Repository\MetricDataRepository: '@App\Repository\InfluxDBv2MetricDataRepository'

    App\Resolver\RootResolverMap:
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    # configure Security related services
    App\Security\LoginFormAuthenticator:
        $userProvider: '@security.user.provider.concrete.db_provider'

    Symfony\Component\Ldap\LdapInterface: '@app.ldap'

    app.ldap:
        class: 'Symfony\Component\Ldap\Ldap'
        arguments: ['@app.ldap_adapter']
        tags: [ldap]

    app.ldap_adapter:
        class: 'Symfony\Component\Ldap\Adapter\ExtLdap\Adapter'
        arguments:
          - connection_string: '%env(LDAP_URL)%'
            # encryption: tls
            options:
              protocol_version: 3
              referrals: false

    Symfony\Component\Ldap\Security\CheckLdapCredentialsListener:
        arguments: ['@security.ldap_locator']
        tags:
          - { name: kernel.event_subscriber, dispatcher: security.event_dispatcher.main }
          - { name: kernel.event_subscriber, dispatcher: security.event_dispatcher.api }
