# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Colormaps/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # configure which implementation of MetricDataRepository
    # to inject in other services such as JobData and JobStats
    App\Repository\MetricDataRepository: '@App\Repository\InfluxDBv2MetricDataRepository'

    App\Resolver\RootResolverMap:
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
        tags:
            - ldap
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            - connection_string: 'ldaps://hpcldap.rrze.uni-erlangen.de'
              #host: 'ldaps://hpcldap.rrze.uni-erlangen.de'
              #port: 389
              #encryption: tls
              options:
                  protocol_version: 3
                  referrals: false
