# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Colormaps/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # configure which implementation of MetricDataRepository
    # to inject in other services such as JobData and JobStats
    App\Repository\MetricDataRepository: '@App\Repository\InfluxDBv2MetricDataRepository'

    App\Resolver\RootResolverMap:
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    App\Security\LoginFormAuthenticator:
        $userProvider: '@security.user.provider.concrete.db_provider'

    app.ldap:
        class: 'Symfony\Component\Ldap\Ldap'
        arguments: ['@app.ldap_adapter']
        tags: [ldap]  # <-- this is important!

    app.ldap_adapter:
        class: 'Symfony\Component\Ldap\Adapter\ExtLdap\Adapter'
        arguments:
          - connection_string: 'ldap://cc-ldap'
            # encryption: tls
            options:
              protocol_version: 3
              referrals: false

    Symfony\Component\Ldap\Security\CheckLdapCredentialsListener:
        arguments: ['@security.ldap_locator']
        tags:
          - { name: kernel.event_subscriber, dispatcher: security.event_dispatcher.main }
          - { name: kernel.event_subscriber, dispatcher: security.event_dispatcher.api }

    # Symfony\Component\Ldap\Security\CheckLdapCredentialsListener:
    #     tags:
    #         - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\CheckPassportEvent }
